### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by v3ss0n** [tony612/highlight-column#21] opened 2015-11-01 18:55 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0-beta0-2ec1b18
**System**: "Sabayon Linux
**Thrown From**: [highlight-column](https://github.com/tony612/highlight-column) package, v0.5.0

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /opt/atom/resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (/opt/atom/resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at TextEditor.module.exports.TextEditor.pixelRectForScreenRange (/opt/atom/resources/app.asar/src/text-editor.js:2934:12)
    at Cursor.module.exports.Cursor.getPixelRect (/opt/atom/resources/app.asar/src/cursor.js:681:26)
    at highlight-column.HighlightColumnView.highlightRect (/home/v3ss/.atom/packages/highlight-column/lib/highlight-column-element.coffee:120:26)
    at highlight-column.HighlightColumnView.updateHighlight (/home/v3ss/.atom/packages/highlight-column/lib/highlight-column-element.coffee:86:21)
    at /home/v3ss/.atom/packages/highlight-column/lib/highlight-column-element.coffee:36:24
    at /home/v3ss/.atom/packages/highlight-column/lib/highlight-column-element.coffee:51:18
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at atom-text-editor.TextEditorElement.attachedCallback (/opt/atom/resources/app.asar/src/text-editor-element.js:99:27)
    at atom-pane.PaneElement.activeItemChanged (/opt/atom/resources/app.asar/src/pane-element.js:138:24)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (/opt/atom/resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/opt/atom/resources/app.asar/src/pane.js:312:21)
    at atom-tabs.TabBarView.onMouseDown (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:681:19)
```

### Commands

```
  2x -0:12.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-steam-pirate-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-ruby-on-rails",
      "mobile-preview",
      "atom-html-preview",
      "color-picker",
      "run-command",
      "runcoderun",
      "whitespace",
      "autosave",
      "autocomplete-jedi",
      "autocomplete-plus-async",
      "cute-cursor",
      "pulsing-cursor",
      "neon-selection",
      "atom-lint",
      "animation-showcase",
      "tree-view-open-files",
      "autocomplete",
      "ease-blink",
      "highlight-line",
      "minimap-highlight-selected",
      "markdown-writer",
      "atom-alignment",
      "autocomplete-atom-api",
      "fancy-input",
      "sublime-tabs",
      "spell-check",
      "tool-bar-main",
      "tool-bar",
      "flex-tool-bar",
      "gutter-shadow",
      "local-history",
      "tab-rename",
      "goto",
      "cursor-blink-interval",
      "auto-reveal-in-sidebar",
      "language-javascript-better",
      "block-cursor",
      "block-travel",
      "nuclide-file-tree",
      "vim-mode",
      "autohide-tree-view",
      "pigments"
    ],
    "ignoredNames": [
      "*.pyc",
      "/home/v3ss/workspace/phwa.be/condaenv",
      "/home/v3ss/workspace/phwa.be/pypyenv",
      "*.zip",
      "*.tar",
      ".hg",
      "./node_modules",
      "node_modules"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "steam-pirate-syntax"
    ]
  },
  "highlight-column": {
    "enableHighlight": true,
    "opacity": 0.05
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.8.4
autocomplete-python, v0.9.4
browser-plus, v0.0.53
build, v0.48.0
editorconfig, v1.2.1
ember-tabs, v2.1.0
emmet, v2.3.13
file-icons, v1.6.11
file-type-icons, v0.7.3
highlight-column, v0.5.0
highlight-selected, v0.10.1
language-ember-htmlbars, v0.3.0
language-nim, v0.2.2
linter, v1.10.0
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-flake8, v1.9.1
linter-jshint, v1.2.1
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
minimap, v4.15.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.1
minimap-selection, v4.3.1
nuclide-diff-view, v0.0.32
nuclide-hg-repository, v0.0.32
pdf-view, v0.34.0
script-runner, v1.8.4
steam-pirate-syntax, v0.3.0
symbols-tree-view, v0.10.1
synced-sidebar, v0.4.2
tabs-to-spaces, v0.11.1
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by tony612** [comment] 2015-11-02 13:49
It's weird. I use atom-beta too, but I didn't get this error. And this package doesn't depends on any other packages. Maybe it's caused by some bugs in Atom or anything else? 
I found another issue, which is similar to this https://github.com/atom/atom/issues/9350
It seems related to nuclide?
I'll keep an eye on this issue :)

**Comment by v3ss0n** [comment] 2015-11-03 05:56
Thanks alot.highlight column is very important for me.

**Comment by tony612** [comment] 2016-03-18 14:06
Close this for https://github.com/facebook/nuclide/issues/246

**Closed by tony612** 2016-03-18 14:06 UTC
